name: Déploiement Ansible distant

on:
  push:
    branches:
      - PROD

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Test SSH vers serveur Ansible
        run: |
          ssh -o StrictHostKeyChecking=no user@srv-ansible "hostname"
      - name: Lancer le playbook
        run: |
          ssh user@serveur-ansible \
          "cd /opt/ansible && ansible-playbook -i inventory.ini config-ssh.ymlname: Déploiement Ansible distant

on:
  push:
    branches:
      - PROD

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Test SSH vers serveur Ansible
        run: |
          ssh -o StrictHostKeyChecking=no user@srv-ansible "hostname"
      - name: Lancer le playbook
        run: |
          ssh user@serveur-ansible \
          "cd /opt/ansible && ansible-playbook -i inventory.ini config-ssh.yml
